name: Build docker image

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest
    env:
      registry: ghcr.io/${{ github.repository_owner }}/nginx-jwt-module
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        id: docker_build_image
        uses: docker/build-push-action@v3
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ env.registry }}:latest
          cache-from: type=gha,scope=main
          cache-to: type=gha,mode=max,scope=main
